# ===================================================================
# CONFIGURACIÓN DE RUTAS (SPRING CLOUD GATEWAY)
# ===================================================================

# Ruta para el Microservicio de Autenticación
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# Ruta para el Microservicio de Médicos
spring.cloud.gateway.routes[1].id=medicos-service
spring.cloud.gateway.routes[1].uri=lb://medicos-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/medico/**

# Ruta para el Microservicio de Pacientes
spring.cloud.gateway.routes[2].id=pacientes-service
spring.cloud.gateway.routes[2].uri=lb://pacientes-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/pacientes/**

# Ruta para el Microservicio de Citas
spring.cloud.gateway.routes[3].id=citas-service
spring.cloud.gateway.routes[3].uri=lb://citas-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/citas/**

# Ruta para el Microservicio de Notificaciones
spring.cloud.gateway.routes[4].id=notificacion-service
spring.cloud.gateway.routes[4].uri=lb://notificacion-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/notificacion/**

# Ruta para el Microservicio de Historial
spring.cloud.gateway.routes[5].id=historial-service
spring.cloud.gateway.routes[5].uri=lb://historial-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/historial-medico/**

server.port=8222
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone= http://localhost:8761/eureka/

# ===================================================================
# CONFIGURACIÓN DE LOGS (DEBUG)
# ===================================================================
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.http.server.reactive=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.level.reactor.netty=DEBUG

# CORS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin