#server.port=8091

#spring.datasource.url=jdbc:postgresql://localhost:5432/db_auth
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true

#logging.levels.root: INFO
#logging.levels.root.com.umg.microservicios: WARN
#logging.pattern.console: '%d{yyyy-MM-dd HH:mm:ss} {%thread} %-5level %logger{36} - %msg%n'
#logging.pattern.file: '%d{yyyy-MM-dd HH:mm:ss} {%thread} %-5level %logger{36} - %msg%n'
#logging.file.name: logs/auth-service.log
#logging.file.max-size: 10MB
#logging.file.max-history: 30

# Puerto dinámico asignado por Railway o 8091 en tu local
server.port=${PORT:8091}

# Conexión dinámica a la base de datos db_auth en Railway
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/db_auth
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Registro obligatorio en Eureka Discovery Server
eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

# Configuración de Logs (Mantenemos tu estructura original)
logging.levels.root: INFO
logging.levels.root.com.umg.microservicios: WARN
logging.pattern.console: '%d{yyyy-MM-dd HH:mm:ss} {%thread} %-5level %logger{36} - %msg%n'
logging.pattern.file: '%d{yyyy-MM-dd HH:mm:ss} {%thread} %-5level %logger{36} - %msg%n'
logging.file.name: logs/auth-service.log
logging.file.max-size: 10MB
logging.file.max-history: 30
