#server.port=8761
#eureka.instance.hostname=localhost
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#eureka.client.service-url.defaultZone= http://${eureka.instance.hostname}:${server.port}/eureka/

# Railway asignará el puerto automáticamente. Si no hay, usa el 8761 por defecto.
server.port=${PORT:8761}

# Variable interna de Railway para obtener el dominio público en la nube
eureka.instance.hostname=${RAILWAY_PUBLIC_DOMAIN:localhost}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/

