server.port=8094

spring.datasource.url=jdbc:postgresql://localhost:5432/db_medicos
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

logging.levels.root: INFO
logging.levels.root.com.umg.microservicios: WARN
logging.pattern.console: '%d{yyyy-MM-dd HH:mm:ss} {%thread} %-5level %logger{36} - %msg%n'
logging.pattern.file: '%d{yyyy-MM-dd HH:mm:ss} {%thread} %-5level %logger{36} - %msg%n'
logging.file.name: logs/medicos-service.log
logging.file.max-size: 10MB
logging.file.max-history: 30

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

