# CONFIGURACIÓN DEL SERVIDOR DE CORREO (SMTP)
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=elopez@inforumsol.com
#spring.mail.password=rtbq ykdb nrrf kgbr
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# CONFIGURACIÓN DE CONEXIÓN A RABBITMQ
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

#spring.datasource.url=jdbc:postgresql://localhost:5432/db_notificacion
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true

#logging.levels.root: INFO
#logging.levels.root.com.umg.microservicios: WARN
#logging.pattern.console: '%d{yyyy-MM-dd HH:mm:ss} {%thread} %-5level %logger{36} - %msg%n'
#logging.pattern.file: '%d{yyyy-MM-dd HH:mm:ss} {%thread} %-5level %logger{36} - %msg%n'
#logging.file.name: logs/notificacion-service.log
#logging.file.max-size: 10MB
#logging.file.max-history: 30

# Puerto dinámico asignado por Railway o el puerto por defecto de tu servicio
server.port=${PORT:8098}

# CONFIGURACIÓN DEL SERVIDOR DE CORREO (SMTP) - Se mantiene igual ya que es externo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=elopez@inforumsol.com
spring.mail.password=rtbq ykdb nrrf kgbr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# CONFIGURACIÓN DE CONEXIÓN A RABBITMQ (Usa la URL completa de CloudAMQP en la nube)
spring.rabbitmq.addresses=${RABBITMQ_URL:amqps://vbxbxxvv:J5-d0PPvYUTTdGcSX112J4ahigJM2_wZ@shark.rmq.cloudamqp.com/vbxbxxvv}

# Conexión dinámica a la base de datos db_notificacion en Railway
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/db_notificacion
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Mantener en update para no borrar tus tablas de la nube
spring.jpa.hibernate.ddl-auto=update

# Registro obligatorio en Eureka Discovery Server
eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

# Configuración de Logs
logging.levels.root: INFO
logging.levels.root.com.umg.microservicios: WARN
logging.pattern.console: '%d{yyyy-MM-dd HH:mm:ss} {%thread} %-5level %logger{36} - %msg%n'
logging.pattern.file: '%d{yyyy-MM-dd HH:mm:ss} {%thread} %-5level %logger{36} - %msg%n'
logging.file.name: logs/notificacion-service.log
logging.file.max-size: 10MB
logging.file.max-history: 30