spring.application.name=medicos-service
# En local buscará en localhost, en la nube usará la URL de Railway que le daremos
spring.config.import=optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
