#spring.application.name=discovery-server
#spring.config.import= optional:configserver:http://localhost:8888

spring.application.name=discovery-server

# En local busca en localhost:8888. En la nube usará la URL que le inyectemos del config-server.
spring.config.import=optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}