-- public.especialidad definition

-- Drop table

-- DROP TABLE especialidad;

CREATE TABLE especialidad (
	id_especialidad int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	nombre varchar(100) NOT NULL,
	descripcion varchar(255) NULL,
	CONSTRAINT especialidad_pkey PRIMARY KEY (id_especialidad)
);


-- public.recepcionista definition

-- Drop table

-- DROP TABLE recepcionista;

CREATE TABLE recepcionista (
	id_recepcionista int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	nombre varchar(100) NOT NULL,
	apellido varchar(100) NOT NULL,
	telefono varchar(20) NULL,
	email varchar(100) NULL,
	CONSTRAINT recepcionista_pkey PRIMARY KEY (id_recepcionista)
);


-- public.seguro_medico definition

-- Drop table

-- DROP TABLE seguro_medico;

CREATE TABLE seguro_medico (
	id_seguro int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	nombre_aseguradora varchar(150) NOT NULL,
	numero_poliza varchar(80) NOT NULL,
	fecha_vencimiento date NULL,
	CONSTRAINT seguro_medico_pkey PRIMARY KEY (id_seguro)
);


-- public.medico definition

-- Drop table

-- DROP TABLE medico;

CREATE TABLE medico (
	id_medico int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	nombre varchar(100) NOT NULL,
	apellido varchar(100) NOT NULL,
	id_especialidad int4 NOT NULL,
	disponible bool NOT NULL DEFAULT true,
	telefono varchar(20) NULL,
	email varchar(100) NULL,
	CONSTRAINT medico_pkey PRIMARY KEY (id_medico),
	CONSTRAINT medico_id_especialidad_fkey FOREIGN KEY (id_especialidad) REFERENCES especialidad(id_especialidad) DEFERRABLE
);


-- public.paciente definition

-- Drop table

-- DROP TABLE paciente;

CREATE TABLE paciente (
	id_paciente int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	numero_identificacion varchar(20) NOT NULL,
	nombre varchar(100) NOT NULL,
	apellido varchar(100) NOT NULL,
	fecha_nacimiento date NOT NULL,
	direccion varchar(255) NOT NULL,
	telefono varchar(20) NOT NULL,
	email varchar(100) NULL,
	id_seguro int4 NULL,
	fecha_registro timestamp NOT NULL DEFAULT now(),
	id_recepcionista int4 NOT NULL,
	id_usuario int4 NOT NULL,
	CONSTRAINT paciente_numero_identificacion_key UNIQUE (numero_identificacion),
	CONSTRAINT paciente_pkey PRIMARY KEY (id_paciente),
	CONSTRAINT paciente_id_recepcionista_fkey FOREIGN KEY (id_recepcionista) REFERENCES recepcionista(id_recepcionista) DEFERRABLE,
	CONSTRAINT paciente_id_seguro_fkey FOREIGN KEY (id_seguro) REFERENCES seguro_medico(id_seguro) DEFERRABLE
);
CREATE INDEX idx_paciente_identificacion ON public.paciente USING btree (numero_identificacion);


-- public.cita definition

-- Drop table

-- DROP TABLE cita;

CREATE TABLE cita (
	id_cita int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	id_paciente int4 NOT NULL,
	id_medico int4 NOT NULL,
	id_recepcionista int4 NOT NULL,
	fecha_cita date NOT NULL,
	hora_cita time NOT NULL,
	ubicacion varchar(150) NULL,
	estado varchar(20) NOT NULL DEFAULT 'PENDIENTE'::character varying,
	observaciones varchar(500) NULL,
	fecha_creacion timestamp NOT NULL DEFAULT now(),
	CONSTRAINT chk_estado_cita CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'CONFIRMADA'::character varying, 'CANCELADA'::character varying, 'COMPLETADA'::character varying])::text[]))),
	CONSTRAINT cita_pkey PRIMARY KEY (id_cita),
	CONSTRAINT cita_id_medico_fkey FOREIGN KEY (id_medico) REFERENCES medico(id_medico) DEFERRABLE,
	CONSTRAINT cita_id_paciente_fkey FOREIGN KEY (id_paciente) REFERENCES paciente(id_paciente) DEFERRABLE,
	CONSTRAINT cita_id_recepcionista_fkey FOREIGN KEY (id_recepcionista) REFERENCES recepcionista(id_recepcionista) DEFERRABLE
);
CREATE INDEX idx_cita_fecha ON public.cita USING btree (fecha_cita);
CREATE INDEX idx_cita_medico ON public.cita USING btree (id_medico);
CREATE INDEX idx_cita_paciente ON public.cita USING btree (id_paciente);