spring.application.name=config-server
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config
server.port=${PORT:8888}

# Conexión al RabbitMQ de la nube (CloudAMQP) para el bus de datos
spring.rabbitmq.addresses=${RABBITMQ_URL:amqps://vbxbxxvv:J5-d0PPvYUTTdGcSX112J4ahigJM2_wZ@shark.rmq.cloudamqp.com/vbxbxxvv}




#amqps://vbxbxxvv:J5-d0PPvYUTTdGcSX112J4ahigJM2_wZ@shark.rmq.cloudamqp.com/vbxbxxvv